#!/bin/bash
source ../output
if [[ $name ]]; then
        docker build -t me/site $PWD
        docker run --name $name -p $PORT:8080 -d me/site
else
        read -p "Не найдено имя программы, запустить установку сейчас? (Y/N)" -n 1 answer
        case $answer in
                y|Y)
                        echo -e "\n Запускаю.."
                        cd ..
                        bash dockerInstall
                        ;;
                n|N)
                        ;;
                *)
                        ;;
        esac
fi
